language: haxe

install: 
  - go version
  - ./goinstall.sh
  - source ~/.bashrc
  - export GOPATH=~/gopath
  - export GOROOT=/usr/local/go
  - export GOTOOLDIR=/usr/local/go/pkg/tool/linux_amd64
  - export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH
  - export GOPATH=~/gopath
  - sudo chmod 777 $GOPATH
  - go env
  - go version
  - go get -d -v . 

script: 
  - go test -v .
